### ISSUE TITLE
Feedback is welcome

### ISSUE THREAD

**Issue by microic** [microic/niy#1]
**Email:** multisilicon@gmail.com

**Comment by Cypher1** [comment]
Would love to review this but it's impossible to do so without a) access to the full source (not the compiled version) and b) adding a License so that it's clear who work based on this belongs to.

**Comment by microic** [comment]
I  am applying a job from NVdia, I hope NVdia take over this project, and then NVdia will publish the full source code

I add Apache License 2.0 to the project

**Comment by Cypher1** [comment]
Okay. If you could update this issue once source is available I'd love to have a look. Thanks for adding a license.

**Comment by microic** [comment]
No problem

**Comment by microic** [comment]
We start to develop Niy2 which is based on excitement, inhibition and neuron
